version: '3'

services:
  db:
    image: mariadb:10.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Chicken0212!
      MYSQL_DATABASE: pichome
      MYSQL_USER: pichome
      MYSQL_PASSWORD: Pichome
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql

  app:
    image: oaooa/pichome
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      DB_HOST: db
      DB_NAME: pichome
      DB_USER: pichome
      DB_PASSWORD: Pichome
    depends_on:
      - db
      - certbot_init
    volumes:
      - ./data/cert:/etc/nginx/ssl
    command: nginx -g 'daemon off;' # Make sure nginx runs in the foreground

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/cert:/etc/letsencrypt
      - ./data/cert:/var/lib/letsencrypt
      - ./data/cert-etc:/etc/nginx/ssl
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/lib/letsencrypt/ --deploy-hook "nginx -s reload"; sleep 12h & wait $${!}; done;'
    depends_on:
      - app

  certbot_init:
    image: certbot/certbot
    volumes:
      - ./data/cert:/etc/letsencrypt
      - ./data/cert:/var/lib/letsencrypt
    entrypoint: /bin/sh -c 'while ! nc -z app 80; do sleep 1; done; certbot certonly --webroot -w /var/lib/letsencrypt -d www.nekostation.top -d nekostation.top --non-interactive --agree-tos --email lucafang0212@gmail.com --rsa-key-size 2048 --force-renewal;'

volumes:
  certbot-etc:
