version: '3'

services:
  db:
    image: mariadb:10.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Chicken0212!
      MYSQL_DATABASE: pichome
      MYSQL_USER: pichome
      MYSQL_PASSWORD: Pichome
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql

  app:
    image: oaooa/pichome
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      DB_HOST: db
      DB_NAME: pichome
      DB_USER: pichome
      DB_PASSWORD: Pichome
    depends_on:
      - db
    volumes:
      - ./data/cert:/etc/nginx/ssl


