version: '3'

services:
  db:
    image: mariadb:10.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Chicken0212!
      MYSQL_DATABASE: pichome
      MYSQL_USER: pichome
      MYSQL_PASSWORD: Pichome
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql

  app:
    image: oaooa/pichome
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      DB_HOST: db
      DB_NAME: pichome
      DB_USER: pichome
      DB_PASSWORD: Pichome
    depends_on:
      - db
    volumes:
      - ./data/cert:/etc/nginx/ssl

  certbot:
    image: certbot/certbot
    container_name: certbot
    environment:
      NAMESILO_API_KEY: your_namesilo_api_key
    volumes:
      - ./data/cert:/etc/letsencrypt
      - ./data/namesilo.ini:/etc/letsencrypt/namesilo.ini:ro
    entrypoint: >
      /bin/sh -c 'trap exit TERM;
      while :; do
        certbot certonly --dns-namesilo --dns-namesilo-credentials /etc/letsencrypt/namesilo.ini --email lucafang0212@gmail.com --agree-tos --no-eff-email -d nekostation.top -d www.nekostation.top --force-renewal;
        sleep 12h & wait $${!};
      done;'
